const PROJECTS=[['Heating','Boiler Replacement'],['Heating','Hot Water Tank Replacement'],['Heating','Pump Replacement'],['Cooling','Chiller Repair'],['Cooling','Mini Split Installation'],['Rooftop','RTU Replacement'],['Rooftop','Package Unit Repair'],['Repairs','Compressor Replacement'],['Repairs','Motor Replacement'],['Controls','Sensor Replacement'],['Controls','BAS / Controls Upgrade'],['Specialty','Cooling Tower'],['Specialty','Leak Investigation'],['Specialty','PM Findings']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escapeHTML=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let jobs=loadJobs(),category='All',activeJobId=null,selectedType='';
let company=loadCompany(),installPrompt=null;
let voiceRecognition=null,voiceListening=false,voiceBase='';
let knowledge=loadKnowledge();
let photoJobId=localStorage.getItem('albert.photoJob')||'',photoURLs=[];

function loadJobs(){try{return JSON.parse(localStorage.getItem('albert.jobs')||'[]')}catch{return[]}}
function persist(){localStorage.setItem('albert.jobs',JSON.stringify(jobs))}
function loadCompany(){try{return JSON.parse(localStorage.getItem('albert.company')||'{}')}catch{return{}}}
function persistCompany(){localStorage.setItem('albert.company',JSON.stringify(company))}
function loadKnowledge(){try{return JSON.parse(localStorage.getItem('albert.knowledge')||'[]')}catch{return[]}}
function persistKnowledge(){localStorage.setItem('albert.knowledge',JSON.stringify(knowledge))}
function saveIntake(){localStorage.setItem('albert.intake',JSON.stringify({customer:$('#customer').value,description:$('#description').value,selectedType}))}
function restoreIntake(){try{const draft=JSON.parse(localStorage.getItem('albert.intake')||'{}');$('#customer').value=draft.customer||'';$('#description').value=draft.description||'';selectedType=draft.selectedType||''}catch{}score()}
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));localStorage.setItem('albert.page',id);scrollTo(0,0);if(id==='jobs')renderJobs('#allJobs');if(id==='camera'){renderPhotoJobOptions();renderPhotos()}}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function renderJobs(target='#recentJobs'){const el=$(target),list=target==='#recentJobs'?jobs.slice(0,3):jobs;el.innerHTML=list.length?list.map(j=>target==='#allJobs'?`<article class="job job-manage"><button class="job-open" data-job="${escapeHTML(j.id)}"><span><b>${escapeHTML(j.customer)}</b><small>${escapeHTML(j.type||'Unclassified')} · ${new Date(j.updated).toLocaleDateString()}</small></span><span class="status ${j.status==='Approved'?'approved':''}">${escapeHTML(j.status)}</span></button><button class="reuse" data-reuse="${escapeHTML(j.id)}">Reuse</button></article>`:`<button class="job job-button" data-job="${escapeHTML(j.id)}"><span><b>${escapeHTML(j.customer)}</b><small>${escapeHTML(j.type||'Unclassified')} · ${new Date(j.updated).toLocaleDateString()}</small></span><span class="status ${j.status==='Approved'?'approved':''}">${escapeHTML(j.status)}</span></button>`).join(''):'<div class="empty">No drafts yet. Start with a blank proposal or choose a project template.</div>';$$(`${target} [data-job]`).forEach(b=>b.onclick=()=>openJob(b.dataset.job));$$(`${target} [data-reuse]`).forEach(b=>b.onclick=()=>reuseJob(b.dataset.reuse))}
function renderProjects(){const q=$('#projectSearch').value.toLowerCase(),list=PROJECTS.filter(p=>(category==='All'||p[0]===category)&&p.join(' ').toLowerCase().includes(q));$('#projectList').innerHTML=list.map(p=>`<button class="project-row" data-type="${escapeHTML(p[1])}"><span><b>${escapeHTML(p[1])}</b><small>${escapeHTML(p[0])}</small></span><i>›</i></button>`).join('');$$('.project-row').forEach(b=>b.onclick=()=>{selectedType=b.dataset.type;page('intake');$('#analysis').innerHTML=`<b>${escapeHTML(selectedType)}</b><p class="muted">Project selected. Describe the work and Albert will ask for missing details.</p>`;$('#analysis').classList.remove('hidden')})}
function score(){const value=($('#customer').value?35:0)+($('#description').value.length>25?45:$('#description').value?20:0)+(selectedType?20:0);$('#intakeProgress').value=value;$('#score').textContent=value+'% complete'}
async function analyze(){const customer=$('#customer').value.trim(),description=$('#description').value.trim();if(!customer||!description)return toast('Add the customer and job description');const box=$('#analysis');box.classList.remove('hidden');box.innerHTML='<b>Albert is organizing the job…</b>';let result={projectType:selectedType||'Unclassified',summary:description,missingQuestions:[]};try{const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'intake',customer,description,projectType:selectedType})});if(!response.ok)throw Error('AI service unavailable');result=await response.json()}catch{result.offline=true}box.innerHTML=`<b>${escapeHTML(result.projectType||selectedType||'Job intake')}</b><p>${escapeHTML(result.summary||description)}</p>${result.missingQuestions?.length?`<small>Missing information</small><ul>${result.missingQuestions.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>`:''}${result.offline?'<p class="muted">AI is unavailable right now. Your notes are safe.</p>':''}<button class="primary" id="saveDraft">Save and review</button>`;$('#saveDraft').onclick=()=>save(customer,description,result)}
function save(customer,description,result){const job={id:crypto.randomUUID(),customer,description,type:result.projectType||selectedType||'Unclassified',summary:result.summary||description,questions:result.missingQuestions||[],status:'Draft',proposal:'',updated:Date.now()};jobs.unshift(job);persist();resetIntake();renderJobs();toast('Draft saved');openJob(job.id)}
function resetIntake(){$('#customer').value='';$('#description').value='';$('#analysis').classList.add('hidden');selectedType='';localStorage.removeItem('albert.intake');score()}
function openJob(id){const job=jobs.find(j=>j.id===id);if(!job)return;activeJobId=id;localStorage.setItem('albert.activeJob',id);photoJobId=id;localStorage.setItem('albert.photoJob',id);$('#reviewTitle').textContent=job.customer||'Blank proposal';$('#reviewMeta').textContent=`${job.type} · Updated ${new Date(job.updated).toLocaleString()}`;$('#reviewCustomer').value=job.customer==='Untitled Proposal'?'':job.customer;$('#reviewDescription').value=job.description;const questions=$('#reviewQuestions');questions.innerHTML=job.questions?.length?`<b>Confirm before sending</b><ul>${job.questions.map(q=>`<li>${escapeHTML(q)}</li>`).join('')}</ul>`:'';questions.classList.toggle('hidden',!job.questions?.length);$('#proposalText').value=job.proposal||'';$('#proposalPanel').classList.remove('hidden');$('#proposalStatus').textContent=job.status;$('#proposalStatus').classList.toggle('approved',job.status==='Approved');page('review')}
function blankProposal(){const job={id:crypto.randomUUID(),customer:'Untitled Proposal',description:'',type:'Blank template',summary:'',questions:[],status:'Draft',proposal:'',updated:Date.now()};jobs.unshift(job);persist();renderJobs();openJob(job.id);$('#reviewCustomer').focus()}
function reuseJob(id){const source=jobs.find(job=>job.id===id);if(!source)return;const copy={...source,id:crypto.randomUUID(),customer:'Untitled Proposal',status:'Draft',updated:Date.now()};jobs.unshift(copy);persist();renderJobs();openJob(copy.id);$('#reviewCustomer').focus();toast('Reusable copy created')}
async function generateProposal(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;job.description=$('#reviewDescription').value.trim();if(!job.description)return toast('Add field notes first');const button=$('#generateProposal');button.disabled=true;button.textContent='Albert is writing…';try{const companyKnowledge=knowledge.flatMap(item=>item.standards||[]).slice(0,30);const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'proposal',customer:job.customer,projectType:job.type,description:job.description,summary:job.summary,missingQuestions:job.questions,companyKnowledge})});if(!response.ok)throw Error('Proposal service unavailable');const data=await response.json();job.proposal=data.proposal||'';job.status='Needs review';job.updated=Date.now();persist();$('#proposalText').value=job.proposal;$('#proposalPanel').classList.remove('hidden');$('#proposalStatus').textContent=job.status;toast('Proposal ready for review')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Generate proposal'}}
function approveProposal(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;const proposal=$('#proposalText').value.trim();if(!proposal)return toast('Generate or enter a proposal first');job.proposal=proposal;job.description=$('#reviewDescription').value.trim();job.status='Approved';job.updated=Date.now();persist();$('#proposalStatus').textContent='Approved';$('#proposalStatus').classList.add('approved');toast('Proposal approved and saved')}
async function deleteDraft(){const job=jobs.find(j=>j.id===activeJobId);if(!job||!confirm(`Delete ${job.customer}'s draft and its photos?`))return;await deleteJobPhotos(activeJobId);jobs=jobs.filter(j=>j.id!==activeJobId);persist();activeJobId=null;localStorage.removeItem('albert.activeJob');renderJobs();page('jobs');toast('Draft and photos deleted')}
async function copyProposal(){const text=$('#proposalText').value;if(!text)return toast('No proposal to copy');await navigator.clipboard.writeText(text);toast('Proposal copied')}
function saveActiveEdits(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;job.customer=$('#reviewCustomer').value.trim()||'Untitled Proposal';job.description=$('#reviewDescription').value.trim();job.proposal=$('#proposalText').value;job.updated=Date.now();$('#reviewTitle').textContent=job.customer;persist()}
function proposalDocument(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return'';const contact=[company.salesperson,company.phone,company.email].filter(Boolean).join(' · ');return `<header class="proposal-head"><div><h1>${escapeHTML(company.name||'Albert DTS')}</h1><p>${escapeHTML(contact)}</p></div><strong>PROPOSAL</strong></header><div class="proposal-meta"><p><b>Prepared for</b><br>${escapeHTML(job.customer)}</p><p><b>Project</b><br>${escapeHTML(job.type)}</p><p><b>Date</b><br>${new Date().toLocaleDateString()}</p></div><div class="proposal-body">${escapeHTML($('#proposalText').value).replace(/\n/g,'<br>')}</div>${company.warranty?`<section><h3>Warranty</h3><p>${escapeHTML(company.warranty)}</p></section>`:''}${company.terms?`<section><h3>Terms and exclusions</h3><p>${escapeHTML(company.terms)}</p></section>`:''}<div class="signature"><span>Customer approval / signature</span><span>Date</span></div>`}
function previewProposal(){if(!$('#proposalText').value.trim())return toast('Generate or enter a proposal first');saveActiveEdits();$('#printDocument').innerHTML=proposalDocument();$('#printPreview').classList.add('open');$('#printPreview').setAttribute('aria-hidden','false')}
function closePreview(){$('#printPreview').classList.remove('open');$('#printPreview').setAttribute('aria-hidden','true')}
async function shareProposal(){const job=jobs.find(j=>j.id===activeJobId),text=$('#proposalText').value.trim();if(!job||!text)return toast('Generate or enter a proposal first');saveActiveEdits();const share={title:`Proposal for ${job.customer}`,text:`${company.name||'Albert DTS'}\n\n${text}`};if(navigator.share){try{await navigator.share(share);return}catch(error){if(error.name==='AbortError')return}}await navigator.clipboard.writeText(share.text);toast('Proposal copied for sharing')}
function loadCompanyForm(){$('#companyName').value=company.name||'';$('#salesperson').value=company.salesperson||'';$('#companyPhone').value=company.phone||'';$('#companyEmail').value=company.email||'';$('#companyWarranty').value=company.warranty||'';$('#companyTerms').value=company.terms||''}
function saveCompany(event){event.preventDefault();company={name:$('#companyName').value.trim(),salesperson:$('#salesperson').value.trim(),phone:$('#companyPhone').value.trim(),email:$('#companyEmail').value.trim(),warranty:$('#companyWarranty').value.trim(),terms:$('#companyTerms').value.trim()};persistCompany();toast('Company profile saved')}
function renderKnowledge(){const standards=knowledge.flatMap(item=>item.standards||[]);$('#knowledgeCount').textContent=knowledge.length;$('#knowledgePlural').textContent=knowledge.length===1?'':'s';$('#standardCount').textContent=standards.length}
function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(file)})}
function photoDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('albert.photos',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('photos')){const store=db.createObjectStore('photos',{keyPath:'id'});store.createIndex('jobId','jobId')}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function photoStore(mode='readonly'){const db=await photoDB();return{db,store:db.transaction('photos',mode).objectStore('photos')}}
async function compressPhoto(file){const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise(resolve=>canvas.toBlob(blob=>resolve(blob||file),'image/jpeg',.82))}
async function savePhotos(files){if(!photoJobId)return toast('Choose a job before adding photos');$('#photoStatus').textContent='Saving photos…';try{const prepared=[];for(const file of files){let blob;try{blob=await compressPhoto(file)}catch{blob=file}prepared.push({id:crypto.randomUUID(),jobId:photoJobId,name:file.name||'Job photo',type:blob.type,blob,created:Date.now()})}const {db,store}=await photoStore('readwrite');prepared.forEach(photo=>store.put(photo));await new Promise((resolve,reject)=>{store.transaction.oncomplete=resolve;store.transaction.onerror=()=>reject(store.transaction.error)});db.close();await renderPhotos();toast(`${files.length} photo${files.length===1?'':'s'} saved to job`)}catch(error){$('#photoStatus').textContent='Photo could not be saved. Try a smaller image.'}}
async function getJobPhotos(jobId){if(!jobId)return[];const {db,store}=await photoStore();const request=store.index('jobId').getAll(jobId);const photos=await new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return photos.sort((a,b)=>a.created-b.created)}
async function removePhoto(id){const {db,store}=await photoStore('readwrite');store.delete(id);await new Promise((resolve,reject)=>{store.transaction.oncomplete=resolve;store.transaction.onerror=()=>reject(store.transaction.error)});db.close();renderPhotos();toast('Photo removed')}
async function deleteJobPhotos(jobId){const photos=await getJobPhotos(jobId);if(!photos.length)return;const {db,store}=await photoStore('readwrite');photos.forEach(photo=>store.delete(photo.id));await new Promise(resolve=>store.transaction.oncomplete=resolve);db.close()}
function renderPhotoJobOptions(){const select=$('#photoJob'),open=$('#openPhotoJob');if(!jobs.length){select.innerHTML='<option value="">Start or save a proposal first</option>';select.disabled=true;open.disabled=true;photoJobId='';return}select.disabled=false;open.disabled=false;if(!jobs.some(job=>job.id===photoJobId))photoJobId=activeJobId&&jobs.some(job=>job.id===activeJobId)?activeJobId:jobs[0].id;select.innerHTML=jobs.map(job=>`<option value="${escapeHTML(job.id)}">${escapeHTML(job.customer||'Untitled Proposal')} — ${escapeHTML(job.type||'Unclassified')}</option>`).join('');select.value=photoJobId;localStorage.setItem('albert.photoJob',photoJobId)}
async function renderPhotos(){photoURLs.forEach(URL.revokeObjectURL);photoURLs=[];const el=$('#thumbs');if(!photoJobId){el.innerHTML='<div class="empty">Select a saved job before adding photos.</div>';$('#photoStatus').textContent='';return}try{const photos=await getJobPhotos(photoJobId);el.innerHTML=photos.length?photos.map(photo=>{const url=URL.createObjectURL(photo.blob);photoURLs.push(url);return`<div class="photo-card"><img alt="${escapeHTML(photo.name)}" src="${url}"><button class="remove-photo" data-remove-photo="${escapeHTML(photo.id)}" aria-label="Remove ${escapeHTML(photo.name)}">×</button><small>${escapeHTML(photo.name)}</small></div>`}).join(''):'<div class="empty">No photos saved for this job yet.</div>';$$('[data-remove-photo]').forEach(button=>button.onclick=()=>removePhoto(button.dataset.removePhoto));$('#photoStatus').textContent=photos.length?`${photos.length} saved photo${photos.length===1?'':'s'} · Safe after refresh`:'Photos will save automatically.'}catch{$('#photoStatus').textContent='Saved photos could not be loaded.'}}
async function importKnowledge(event){const files=[...event.target.files];if(!files.length)return;const progress=$('#knowledgeProgress');progress.classList.remove('hidden');let added=0,failed=0;progress.innerHTML='<b>Albert is learning…</b><p>Keep Settings open while approved material is analyzed.</p>';for(const file of files.slice(0,5)){if(file.size>4_000_000||!['application/pdf','text/plain'].includes(file.type)){failed++;continue}try{const base64=await fileBase64(file);const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'knowledge',file:{name:file.name,type:file.type,base64}})});const data=await response.json();if(!response.ok)throw Error(data.error||'Training failed');const result=data.knowledge||{},standards=[...(result.standards||[]),...(result.warrantyTerms||[]),...(result.exclusions||[])];knowledge.unshift({id:crypto.randomUUID(),standards,updated:Date.now()});persistKnowledge();renderKnowledge();added++}catch{failed++}}event.target.value='';progress.innerHTML=`<b>${added?`${added} source${added===1?'':'s'} added to Albert`:'No sources were added'}</b><p>${failed?`${failed} file${failed===1?'':'s'} could not be trained. Use PDF or text under 4 MB.`:'The private standards are now active in proposal generation.'}</p>`}
function clearKnowledge(){if(!knowledge.length)return toast('Albert has no training to clear');if(!confirm('Clear all private Albert training from this device?'))return;knowledge=[];persistKnowledge();renderKnowledge();$('#knowledgeProgress').classList.add('hidden');toast('Private training cleared')}
function finishVoice(){voiceListening=false;voiceRecognition=null;$('#voiceBtn').textContent='🎙️ Start speaking';$('#voiceBtn').setAttribute('aria-pressed','false');score();saveIntake()}
function voiceErrorMessage(error){return({not_allowed:'Allow microphone access in your browser settings, then try again',service_not_allowed:'Voice dictation is blocked in this browser',audio_capture:'No microphone was found',network:'Voice dictation needs an internet connection',no_speech:'I did not hear anything—tap and speak again',aborted:'Recording stopped'}[error]||'Voice dictation could not start')}
function toggleVoice(){if(voiceListening&&voiceRecognition){voiceRecognition.stop();return}const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return toast('Use your keyboard microphone—this browser does not support in-app dictation');voiceBase=$('#description').value.trim();let finalText='';voiceRecognition=new Recognition();voiceRecognition.lang='en-US';voiceRecognition.continuous=!/iPhone|iPad|iPod/i.test(navigator.userAgent);voiceRecognition.interimResults=true;voiceRecognition.maxAlternatives=1;voiceRecognition.onstart=()=>{voiceListening=true;$('#voiceBtn').textContent='■ Stop and use notes';$('#voiceBtn').setAttribute('aria-pressed','true');toast('Listening… speak naturally')};voiceRecognition.onresult=event=>{let interim='';for(let i=event.resultIndex;i<event.results.length;i++){const words=event.results[i][0].transcript.trim();if(event.results[i].isFinal)finalText+=(finalText?' ':'')+words;else interim+=(interim?' ':'')+words}const spoken=[finalText,interim].filter(Boolean).join(' ');$('#description').value=[voiceBase,spoken].filter(Boolean).join(voiceBase&&spoken?' ':'');score();saveIntake()};voiceRecognition.onerror=event=>{if(event.error!=='aborted')toast(voiceErrorMessage(event.error))};voiceRecognition.onend=finishVoice;try{voiceRecognition.start()}catch{finishVoice();toast('Tap the microphone once, then speak after it says Listening') }}

$$('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#tellAlbert').onclick=()=>{resetIntake();page('intake')};$('#viewJobs').onclick=()=>page('jobs');$$('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='new'){resetIntake();page('projects');return}page({camera:'camera',drafts:'jobs',teach:'teach',home:'home',jobs:'jobs'}[b.dataset.action])});
const cats=['All',...new Set(PROJECTS.map(x=>x[0]))];$('#categoryChips').innerHTML=cats.map(c=>`<button class="${c==='All'?'active':''}">${c}</button>`).join('');$$('#categoryChips button').forEach(b=>b.onclick=()=>{category=b.textContent;$$('#categoryChips button').forEach(x=>x.classList.toggle('active',x===b));renderProjects()});$('#projectSearch').oninput=renderProjects;$('#customer').oninput=()=>{score();saveIntake()};$('#description').oninput=()=>{score();saveIntake()};$('#reviewCustomer').oninput=saveActiveEdits;$('#reviewDescription').oninput=saveActiveEdits;$('#proposalText').oninput=saveActiveEdits;$('#blankProposal').onclick=blankProposal;$('#projectTemplate').onclick=()=>{resetIntake();page('projects')};$('#analyzeBtn').onclick=analyze;$('#generateProposal').onclick=generateProposal;$('#approveProposal').onclick=approveProposal;$('#deleteDraft').onclick=deleteDraft;$('#copyProposal').onclick=copyProposal;$('#previewProposal').onclick=previewProposal;$('#shareProposal').onclick=shareProposal;$('#closePreview').onclick=closePreview;$('#printProposal').onclick=()=>print();$('#companyForm').onsubmit=saveCompany;
$('#voiceBtn').onclick=toggleVoice;
$('#photoJob').onchange=event=>{photoJobId=event.target.value;localStorage.setItem('albert.photoJob',photoJobId);renderPhotos()};
$('#openPhotoJob').onclick=()=>{if(photoJobId)openJob(photoJobId);else toast('Choose a saved job first')};
async function handlePhotoSelection(event){const files=[...event.target.files];if(files.length)await savePhotos(files);event.target.value=''}
$('#takePhoto').onchange=handlePhotoSelection;
$('#choosePhotos').onchange=handlePhotoSelection;
$('#knowledge').onchange=importKnowledge;
$('#clearKnowledge').onclick=clearKnowledge;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installApp').classList.remove('hidden')});$('#installApp').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').classList.add('hidden')};
renderJobs();renderProjects();restoreIntake();loadCompanyForm();renderKnowledge();const restoredJob=localStorage.getItem('albert.activeJob'),restoredPage=localStorage.getItem('albert.page');if(restoredPage==='review'&&jobs.some(job=>job.id===restoredJob))openJob(restoredJob);else if(['jobs','camera','settings'].includes(restoredPage))page(restoredPage);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
