const PROJECTS=[['Heating','Boiler Replacement'],['Heating','Hot Water Tank Replacement'],['Heating','Pump Replacement'],['Cooling','Chiller Repair'],['Cooling','Mini Split Installation'],['Rooftop','RTU Replacement'],['Rooftop','Package Unit Repair'],['Repairs','Compressor Replacement'],['Repairs','Motor Replacement'],['Controls','Sensor Replacement'],['Controls','BAS / Controls Upgrade'],['Specialty','Cooling Tower'],['Specialty','Leak Investigation'],['Specialty','PM Findings']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escapeHTML=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let jobs=loadJobs(),category='All',activeJobId=null,selectedType='';
let company=loadCompany(),installPrompt=null;
let voiceRecognition=null,voiceListening=false,voiceBase='';
let knowledge=loadKnowledge();

function loadJobs(){try{return JSON.parse(localStorage.getItem('albert.jobs')||'[]')}catch{return[]}}
function persist(){localStorage.setItem('albert.jobs',JSON.stringify(jobs))}
function loadCompany(){try{return JSON.parse(localStorage.getItem('albert.company')||'{}')}catch{return{}}}
function persistCompany(){localStorage.setItem('albert.company',JSON.stringify(company))}
function loadKnowledge(){try{return JSON.parse(localStorage.getItem('albert.knowledge')||'[]')}catch{return[]}}
function persistKnowledge(){localStorage.setItem('albert.knowledge',JSON.stringify(knowledge))}
function saveIntake(){localStorage.setItem('albert.intake',JSON.stringify({customer:$('#customer').value,description:$('#description').value,selectedType}))}
function restoreIntake(){try{const draft=JSON.parse(localStorage.getItem('albert.intake')||'{}');$('#customer').value=draft.customer||'';$('#description').value=draft.description||'';selectedType=draft.selectedType||''}catch{}score()}
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo(0,0);if(id==='jobs')renderJobs('#allJobs')}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function renderJobs(target='#recentJobs'){const el=$(target),list=target==='#recentJobs'?jobs.slice(0,3):jobs;el.innerHTML=list.length?list.map(j=>`<button class="job job-button" data-job="${escapeHTML(j.id)}"><span><b>${escapeHTML(j.customer)}</b><small>${escapeHTML(j.type||'Unclassified')} · ${new Date(j.updated).toLocaleDateString()}</small></span><span class="status ${j.status==='Approved'?'approved':''}">${escapeHTML(j.status)}</span></button>`).join(''):'<div class="empty">No drafts yet. Tell Albert about your first job.</div>';$$(`${target} [data-job]`).forEach(b=>b.onclick=()=>openJob(b.dataset.job))}
function renderProjects(){const q=$('#projectSearch').value.toLowerCase(),list=PROJECTS.filter(p=>(category==='All'||p[0]===category)&&p.join(' ').toLowerCase().includes(q));$('#projectList').innerHTML=list.map(p=>`<button class="project-row" data-type="${escapeHTML(p[1])}"><span><b>${escapeHTML(p[1])}</b><small>${escapeHTML(p[0])}</small></span><i>›</i></button>`).join('');$$('.project-row').forEach(b=>b.onclick=()=>{selectedType=b.dataset.type;page('intake');$('#analysis').innerHTML=`<b>${escapeHTML(selectedType)}</b><p class="muted">Project selected. Describe the work and Albert will ask for missing details.</p>`;$('#analysis').classList.remove('hidden')})}
function score(){const value=($('#customer').value?35:0)+($('#description').value.length>25?45:$('#description').value?20:0)+(selectedType?20:0);$('#intakeProgress').value=value;$('#score').textContent=value+'% complete'}
async function analyze(){const customer=$('#customer').value.trim(),description=$('#description').value.trim();if(!customer||!description)return toast('Add the customer and job description');const box=$('#analysis');box.classList.remove('hidden');box.innerHTML='<b>Albert is organizing the job…</b>';let result={projectType:selectedType||'Unclassified',summary:description,missingQuestions:[]};try{const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'intake',customer,description,projectType:selectedType})});if(!response.ok)throw Error('AI service unavailable');result=await response.json()}catch{result.offline=true}box.innerHTML=`<b>${escapeHTML(result.projectType||selectedType||'Job intake')}</b><p>${escapeHTML(result.summary||description)}</p>${result.missingQuestions?.length?`<small>Missing information</small><ul>${result.missingQuestions.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>`:''}${result.offline?'<p class="muted">AI is unavailable right now. Your notes are safe.</p>':''}<button class="primary" id="saveDraft">Save and review</button>`;$('#saveDraft').onclick=()=>save(customer,description,result)}
function save(customer,description,result){const job={id:crypto.randomUUID(),customer,description,type:result.projectType||selectedType||'Unclassified',summary:result.summary||description,questions:result.missingQuestions||[],status:'Draft',proposal:'',updated:Date.now()};jobs.unshift(job);persist();resetIntake();renderJobs();toast('Draft saved');openJob(job.id)}
function resetIntake(){$('#customer').value='';$('#description').value='';$('#analysis').classList.add('hidden');selectedType='';localStorage.removeItem('albert.intake');score()}
function openJob(id){const job=jobs.find(j=>j.id===id);if(!job)return;activeJobId=id;$('#reviewTitle').textContent=job.customer;$('#reviewMeta').textContent=`${job.type} · Updated ${new Date(job.updated).toLocaleString()}`;$('#reviewDescription').value=job.description;const questions=$('#reviewQuestions');questions.innerHTML=job.questions?.length?`<b>Confirm before sending</b><ul>${job.questions.map(q=>`<li>${escapeHTML(q)}</li>`).join('')}</ul>`:'';questions.classList.toggle('hidden',!job.questions?.length);$('#proposalText').value=job.proposal||'';$('#proposalPanel').classList.remove('hidden');$('#proposalStatus').textContent=job.status;$('#proposalStatus').classList.toggle('approved',job.status==='Approved');page('review')}
async function generateProposal(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;job.description=$('#reviewDescription').value.trim();if(!job.description)return toast('Add field notes first');const button=$('#generateProposal');button.disabled=true;button.textContent='Albert is writing…';try{const companyKnowledge=knowledge.flatMap(item=>item.standards||[]).slice(0,30);const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'proposal',customer:job.customer,projectType:job.type,description:job.description,summary:job.summary,missingQuestions:job.questions,companyKnowledge})});if(!response.ok)throw Error('Proposal service unavailable');const data=await response.json();job.proposal=data.proposal||'';job.status='Needs review';job.updated=Date.now();persist();$('#proposalText').value=job.proposal;$('#proposalPanel').classList.remove('hidden');$('#proposalStatus').textContent=job.status;toast('Proposal ready for review')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Generate proposal'}}
function approveProposal(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;const proposal=$('#proposalText').value.trim();if(!proposal)return toast('Generate or enter a proposal first');job.proposal=proposal;job.description=$('#reviewDescription').value.trim();job.status='Approved';job.updated=Date.now();persist();$('#proposalStatus').textContent='Approved';$('#proposalStatus').classList.add('approved');toast('Proposal approved and saved')}
function deleteDraft(){const job=jobs.find(j=>j.id===activeJobId);if(!job||!confirm(`Delete ${job.customer}'s draft?`))return;jobs=jobs.filter(j=>j.id!==activeJobId);persist();activeJobId=null;renderJobs();page('jobs');toast('Draft deleted')}
async function copyProposal(){const text=$('#proposalText').value;if(!text)return toast('No proposal to copy');await navigator.clipboard.writeText(text);toast('Proposal copied')}
function saveActiveEdits(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;job.description=$('#reviewDescription').value.trim();job.proposal=$('#proposalText').value;job.updated=Date.now();persist()}
function proposalDocument(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return'';const contact=[company.salesperson,company.phone,company.email].filter(Boolean).join(' · ');return `<header class="proposal-head"><div><h1>${escapeHTML(company.name||'Albert DTS')}</h1><p>${escapeHTML(contact)}</p></div><strong>PROPOSAL</strong></header><div class="proposal-meta"><p><b>Prepared for</b><br>${escapeHTML(job.customer)}</p><p><b>Project</b><br>${escapeHTML(job.type)}</p><p><b>Date</b><br>${new Date().toLocaleDateString()}</p></div><div class="proposal-body">${escapeHTML($('#proposalText').value).replace(/\n/g,'<br>')}</div>${company.warranty?`<section><h3>Warranty</h3><p>${escapeHTML(company.warranty)}</p></section>`:''}${company.terms?`<section><h3>Terms and exclusions</h3><p>${escapeHTML(company.terms)}</p></section>`:''}<div class="signature"><span>Customer approval / signature</span><span>Date</span></div>`}
function previewProposal(){if(!$('#proposalText').value.trim())return toast('Generate or enter a proposal first');saveActiveEdits();$('#printDocument').innerHTML=proposalDocument();$('#printPreview').classList.add('open');$('#printPreview').setAttribute('aria-hidden','false')}
function closePreview(){$('#printPreview').classList.remove('open');$('#printPreview').setAttribute('aria-hidden','true')}
async function shareProposal(){const job=jobs.find(j=>j.id===activeJobId),text=$('#proposalText').value.trim();if(!job||!text)return toast('Generate or enter a proposal first');saveActiveEdits();const share={title:`Proposal for ${job.customer}`,text:`${company.name||'Albert DTS'}\n\n${text}`};if(navigator.share){try{await navigator.share(share);return}catch(error){if(error.name==='AbortError')return}}await navigator.clipboard.writeText(share.text);toast('Proposal copied for sharing')}
function loadCompanyForm(){$('#companyName').value=company.name||'';$('#salesperson').value=company.salesperson||'';$('#companyPhone').value=company.phone||'';$('#companyEmail').value=company.email||'';$('#companyWarranty').value=company.warranty||'';$('#companyTerms').value=company.terms||''}
function saveCompany(event){event.preventDefault();company={name:$('#companyName').value.trim(),salesperson:$('#salesperson').value.trim(),phone:$('#companyPhone').value.trim(),email:$('#companyEmail').value.trim(),warranty:$('#companyWarranty').value.trim(),terms:$('#companyTerms').value.trim()};persistCompany();toast('Company profile saved')}
function renderKnowledge(){const standards=knowledge.flatMap(item=>item.standards||[]);$('#knowledgeCount').textContent=knowledge.length;$('#standardCount').textContent=standards.length;$('#knowledgeScore').textContent=knowledge.length?Math.min(100,knowledge.length*20)+'%':'0%';$('#knowledgeList').innerHTML=knowledge.length?knowledge.map(item=>`<article class="job"><span><b>${escapeHTML(item.name)}</b><small>${escapeHTML(item.summary||'Approved company source')}</small></span><button class="back" data-remove-knowledge="${escapeHTML(item.id)}">Remove</button></article>`).join(''):'<div class="empty">No approved sources yet.</div>';$$('[data-remove-knowledge]').forEach(button=>button.onclick=()=>{knowledge=knowledge.filter(item=>item.id!==button.dataset.removeKnowledge);persistKnowledge();renderKnowledge();toast('Source removed')})}
function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(file)})}
async function importKnowledge(event){const files=[...event.target.files];if(!files.length)return;const progress=$('#knowledgeProgress');progress.classList.remove('hidden');for(const file of files.slice(0,5)){if(file.size>4_000_000){progress.innerHTML=`<b>${escapeHTML(file.name)}</b><p>File is over 4 MB. Use a smaller PDF or text file.</p>`;continue}if(!['application/pdf','text/plain'].includes(file.type)){progress.innerHTML=`<b>${escapeHTML(file.name)}</b><p>Convert this file to PDF or plain text, then try again.</p>`;continue}progress.innerHTML=`<b>Teaching Albert…</b><p>Reading ${escapeHTML(file.name)}</p>`;try{const base64=await fileBase64(file);const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'knowledge',file:{name:file.name,type:file.type,base64}})});const data=await response.json();if(!response.ok)throw Error(data.error||'Upload failed');const result=data.knowledge||{};knowledge.unshift({id:crypto.randomUUID(),name:file.name,summary:result.summary||'',standards:[...(result.standards||[]),...(result.warrantyTerms||[]),...(result.exclusions||[])],updated:Date.now()});persistKnowledge();renderKnowledge();progress.innerHTML=`<b>${escapeHTML(file.name)} added</b><p>Albert extracted supported company standards.</p>`}catch(error){progress.innerHTML=`<b>${escapeHTML(file.name)} was not added</b><p>${escapeHTML(error.message)}</p>`}}event.target.value=''}
function finishVoice(){voiceListening=false;voiceRecognition=null;$('#voiceBtn').textContent='🎙️ Start speaking';$('#voiceBtn').setAttribute('aria-pressed','false');score();saveIntake()}
function voiceErrorMessage(error){return({not_allowed:'Allow microphone access in your browser settings, then try again',service_not_allowed:'Voice dictation is blocked in this browser',audio_capture:'No microphone was found',network:'Voice dictation needs an internet connection',no_speech:'I did not hear anything—tap and speak again',aborted:'Recording stopped'}[error]||'Voice dictation could not start')}
function toggleVoice(){if(voiceListening&&voiceRecognition){voiceRecognition.stop();return}const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return toast('Use your keyboard microphone—this browser does not support in-app dictation');voiceBase=$('#description').value.trim();let finalText='';voiceRecognition=new Recognition();voiceRecognition.lang='en-US';voiceRecognition.continuous=!/iPhone|iPad|iPod/i.test(navigator.userAgent);voiceRecognition.interimResults=true;voiceRecognition.maxAlternatives=1;voiceRecognition.onstart=()=>{voiceListening=true;$('#voiceBtn').textContent='■ Stop and use notes';$('#voiceBtn').setAttribute('aria-pressed','true');toast('Listening… speak naturally')};voiceRecognition.onresult=event=>{let interim='';for(let i=event.resultIndex;i<event.results.length;i++){const words=event.results[i][0].transcript.trim();if(event.results[i].isFinal)finalText+=(finalText?' ':'')+words;else interim+=(interim?' ':'')+words}const spoken=[finalText,interim].filter(Boolean).join(' ');$('#description').value=[voiceBase,spoken].filter(Boolean).join(voiceBase&&spoken?' ':'');score();saveIntake()};voiceRecognition.onerror=event=>{if(event.error!=='aborted')toast(voiceErrorMessage(event.error))};voiceRecognition.onend=finishVoice;try{voiceRecognition.start()}catch{finishVoice();toast('Tap the microphone once, then speak after it says Listening') }}

$$('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#tellAlbert').onclick=()=>{resetIntake();page('intake')};$('#viewJobs').onclick=()=>page('jobs');$$('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='new'){resetIntake();page('projects');return}page({camera:'camera',drafts:'jobs',teach:'teach',home:'home',jobs:'jobs'}[b.dataset.action])});
const cats=['All',...new Set(PROJECTS.map(x=>x[0]))];$('#categoryChips').innerHTML=cats.map(c=>`<button class="${c==='All'?'active':''}">${c}</button>`).join('');$$('#categoryChips button').forEach(b=>b.onclick=()=>{category=b.textContent;$$('#categoryChips button').forEach(x=>x.classList.toggle('active',x===b));renderProjects()});$('#projectSearch').oninput=renderProjects;$('#customer').oninput=()=>{score();saveIntake()};$('#description').oninput=()=>{score();saveIntake()};$('#reviewDescription').oninput=saveActiveEdits;$('#proposalText').oninput=saveActiveEdits;$('#analyzeBtn').onclick=analyze;$('#generateProposal').onclick=generateProposal;$('#approveProposal').onclick=approveProposal;$('#deleteDraft').onclick=deleteDraft;$('#copyProposal').onclick=copyProposal;$('#previewProposal').onclick=previewProposal;$('#shareProposal').onclick=shareProposal;$('#closePreview').onclick=closePreview;$('#printProposal').onclick=()=>print();$('#companyForm').onsubmit=saveCompany;
$('#voiceBtn').onclick=toggleVoice;
$('#photos').onchange=e=>{$('#thumbs').innerHTML=[...e.target.files].map(f=>`<img alt="Job photo" src="${URL.createObjectURL(f)}">`).join('');toast(`${e.target.files.length} photo${e.target.files.length===1?'':'s'} selected`)};
$('#knowledge').onchange=importKnowledge;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installApp').classList.remove('hidden')});$('#installApp').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').classList.add('hidden')};
renderJobs();renderProjects();restoreIntake();loadCompanyForm();renderKnowledge();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
