const PROJECTS=[['Heating','Boiler Replacement'],['Heating','Hot Water Tank Replacement'],['Heating','Pump Replacement'],['Cooling','Chiller Repair'],['Cooling','Condenser Replacement'],['Cooling','Mini Split Installation'],['Rooftop','RTU Replacement'],['Rooftop','Package Unit Repair'],['Repairs','Compressor Replacement'],['Repairs','Motor Replacement'],['Controls','Sensor Replacement'],['Controls','BAS / Controls Upgrade'],['Specialty','Cooling Tower'],['Specialty','Leak Investigation'],['Specialty','PM Findings'],['Agreements','TSA Agreement'],['General','Small Proposal']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escapeHTML=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let jobs=loadJobs(),category='All',activeJobId=null,selectedType='';
let company=loadCompany(),installPrompt=null;
let voiceRecognition=null,voiceListening=false,voiceBase='';
let knowledge=loadKnowledge(),knowledgeQueue=[];
let photoJobId=localStorage.getItem('albert.photoJob')||'',photoURLs=[];
let learning=loadLearning(),outlookConfig=null,outlookReplyContext=null;

function loadJobs(){try{return JSON.parse(localStorage.getItem('albert.jobs')||'[]')}catch{return[]}}
function persist(){localStorage.setItem('albert.jobs',JSON.stringify(jobs))}
function loadCompany(){try{return JSON.parse(localStorage.getItem('albert.company')||'{}')}catch{return{}}}
function persistCompany(){localStorage.setItem('albert.company',JSON.stringify(company))}
function loadKnowledge(){try{return JSON.parse(localStorage.getItem('albert.knowledge')||'[]')}catch{return[]}}
function persistKnowledge(){localStorage.setItem('albert.knowledge',JSON.stringify(knowledge))}
function loadLearning(){try{return JSON.parse(localStorage.getItem('albert.learning')||'[]')}catch{return[]}}
function persistLearning(){localStorage.setItem('albert.learning',JSON.stringify(learning));renderLearning()}
function saveIntake(){localStorage.setItem('albert.intake',JSON.stringify({customer:$('#customer').value,description:$('#description').value,selectedType}))}
function restoreIntake(){try{const draft=JSON.parse(localStorage.getItem('albert.intake')||'{}');$('#customer').value=draft.customer||'';$('#description').value=draft.description||'';selectedType=draft.selectedType||''}catch{}score()}
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));localStorage.setItem('albert.page',id);scrollTo(0,0);if(id==='jobs')renderJobs('#allJobs');if(id==='camera'){renderPhotoJobOptions();renderPhotos()}}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function renderJobs(target='#recentJobs'){const el=$(target),list=target==='#recentJobs'?jobs.slice(0,3):jobs;el.innerHTML=list.length?list.map(j=>target==='#allJobs'?`<article class="job job-manage"><button class="job-open" data-job="${escapeHTML(j.id)}"><span><b>${escapeHTML(j.customer)}</b><small>${escapeHTML(j.type||'Unclassified')} · ${new Date(j.updated).toLocaleDateString()}</small></span><span class="status ${j.status==='Approved'?'approved':''}">${escapeHTML(j.status)}</span></button><button class="reuse" data-reuse="${escapeHTML(j.id)}">Reuse</button></article>`:`<button class="job job-button" data-job="${escapeHTML(j.id)}"><span><b>${escapeHTML(j.customer)}</b><small>${escapeHTML(j.type||'Unclassified')} · ${new Date(j.updated).toLocaleDateString()}</small></span><span class="status ${j.status==='Approved'?'approved':''}">${escapeHTML(j.status)}</span></button>`).join(''):'<div class="empty">No drafts yet. Start with a blank proposal or choose a project template.</div>';$$(`${target} [data-job]`).forEach(b=>b.onclick=()=>openJob(b.dataset.job));$$(`${target} [data-reuse]`).forEach(b=>b.onclick=()=>reuseJob(b.dataset.reuse))}
function renderProjects(){const q=$('#projectSearch').value.toLowerCase(),list=PROJECTS.filter(p=>(category==='All'||p[0]===category)&&p.join(' ').toLowerCase().includes(q));$('#projectList').innerHTML=list.map(p=>`<button class="project-row" data-type="${escapeHTML(p[1])}"><span><b>${escapeHTML(p[1])}</b><small>${escapeHTML(p[0])}</small></span><i>›</i></button>`).join('');$$('.project-row').forEach(b=>b.onclick=()=>{selectedType=b.dataset.type;page('intake');$('#analysis').innerHTML=`<b>${escapeHTML(selectedType)}</b><p class="muted">Project selected. Describe the work and Albert will ask for missing details.</p>`;$('#analysis').classList.remove('hidden')})}
function score(){const value=($('#customer').value?35:0)+($('#description').value.length>25?45:$('#description').value?20:0)+(selectedType?20:0);$('#intakeProgress').value=value;$('#score').textContent=value+'% complete'}
async function analyze(){const customer=$('#customer').value.trim(),description=$('#description').value.trim();if(!customer||!description)return toast('Add the customer and job description');const box=$('#analysis');box.classList.remove('hidden');box.innerHTML='<b>Albert is organizing the job…</b>';let result={projectType:selectedType||'Unclassified',summary:description,missingQuestions:[]};try{const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'intake',customer,description,projectType:selectedType})});if(!response.ok)throw Error('AI service unavailable');result=await response.json()}catch{result.offline=true}box.innerHTML=`<b>${escapeHTML(result.projectType||selectedType||'Job intake')}</b><p>${escapeHTML(result.summary||description)}</p>${result.missingQuestions?.length?`<small>Missing information</small><ul>${result.missingQuestions.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>`:''}${result.offline?'<p class="muted">AI is unavailable right now. Your notes are safe.</p>':''}<button class="primary" id="saveDraft">Save and review</button>`;$('#saveDraft').onclick=()=>save(customer,description,result)}
function save(customer,description,result){const job={id:crypto.randomUUID(),customer,description,type:result.projectType||selectedType||'Unclassified',summary:result.summary||description,extractedFields:result.extractedFields||{},questions:result.missingQuestions||[],missingAnswers:{},status:'Draft',proposal:'',updated:Date.now()};jobs.unshift(job);persist();resetIntake();renderJobs();toast('Draft saved');openJob(job.id)}
function resetIntake(){$('#customer').value='';$('#description').value='';$('#analysis').classList.add('hidden');selectedType='';localStorage.removeItem('albert.intake');score()}
function openJob(id){const job=jobs.find(j=>j.id===id);if(!job)return;activeJobId=id;localStorage.setItem('albert.activeJob',id);photoJobId=id;localStorage.setItem('albert.photoJob',id);$('#reviewTitle').textContent=job.customer||'Blank proposal';$('#reviewMeta').textContent=`${job.type} · Updated ${new Date(job.updated).toLocaleString()}`;$('#reviewCustomer').value=job.customer==='Untitled Proposal'?'':job.customer;$('#reviewDescription').value=job.description;$('#proposalRecipient').value=job.recipient||'';const questions=$('#reviewQuestions'),answers=job.missingAnswers||{};questions.innerHTML=job.questions?.length?`<b>Albert still needs</b><p class="muted fine-print">Answer what you know. Leave unknown details blank—Albert will flag assumptions instead of guessing.</p>${job.questions.map((q,index)=>`<label>${escapeHTML(q)}<input data-missing-answer="${index}" value="${escapeHTML(answers[index]||'')}" placeholder="Answer or leave blank"></label>`).join('')}`:'';questions.classList.toggle('hidden',!job.questions?.length);$$('[data-missing-answer]').forEach(input=>input.oninput=saveActiveEdits);$('#proposalText').value=job.proposal||'';$('#proposalPanel').classList.remove('hidden');$('#proposalStatus').textContent=job.status;$('#proposalStatus').classList.toggle('approved',job.status==='Approved');page('review')}
function blankProposal(){const job={id:crypto.randomUUID(),customer:'Untitled Proposal',description:'',type:'Blank template',summary:'',questions:[],status:'Draft',proposal:'',updated:Date.now()};jobs.unshift(job);persist();renderJobs();openJob(job.id);$('#reviewCustomer').focus()}
function reuseJob(id){const source=jobs.find(job=>job.id===id);if(!source)return;const copy={...source,id:crypto.randomUUID(),customer:'Untitled Proposal',status:'Draft',aiDraft:'',updated:Date.now()};jobs.unshift(copy);persist();renderJobs();openJob(copy.id);$('#reviewCustomer').focus();toast('Reusable copy created')}
async function generateProposal(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;saveActiveEdits();if(!job.description)return toast('Add field notes first');const button=$('#generateProposal');button.disabled=true;button.textContent='Albert is writing…';try{const companyKnowledge=knowledge.flatMap(item=>item.reusableStandards||item.standards||[]).slice(0,30),approvedExamples=learning.slice(0,3).map(x=>({projectType:x.projectType,fieldNotes:x.fieldNotes,approvedProposal:x.approvedProposal}));const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'proposal',customer:job.customer,projectType:job.type,description:job.description,summary:job.summary,extractedFields:job.extractedFields||{},missingQuestions:job.questions,missingAnswers:job.missingAnswers||{},companyKnowledge,approvedExamples})});const data=await response.json();if(!response.ok)throw Error(data.error||'Proposal service unavailable');job.proposal=data.proposal||'';job.aiDraft=job.proposal;job.status='Needs review';job.updated=Date.now();persist();$('#proposalText').value=job.proposal;$('#proposalPanel').classList.remove('hidden');$('#proposalStatus').textContent=job.status;toast('Proposal ready for review')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Generate proposal'}}
function approveProposal(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;const proposal=$('#proposalText').value.trim();if(!proposal)return toast('Generate or enter a proposal first');job.proposal=proposal;job.description=$('#reviewDescription').value.trim();job.status='Approved';job.updated=Date.now();const example={sourceJobId:job.id,projectType:job.type||'Unclassified',fieldNotes:job.description.slice(0,6000),approvedProposal:proposal.slice(0,12000),corrected:Boolean(job.aiDraft&&job.aiDraft.trim()!==proposal),approvedAt:Date.now()};learning=[example,...learning.filter(x=>x.sourceJobId!==job.id)].slice(0,20);persist();persistLearning();$('#proposalStatus').textContent='Approved';$('#proposalStatus').classList.add('approved');toast(example.corrected?'Approved—Albert learned your corrections':'Approved and added to Albert learning')}
async function deleteDraft(){const job=jobs.find(j=>j.id===activeJobId);if(!job||!confirm(`Delete ${job.customer}'s draft and its photos?`))return;await deleteJobPhotos(activeJobId);jobs=jobs.filter(j=>j.id!==activeJobId);persist();activeJobId=null;localStorage.removeItem('albert.activeJob');renderJobs();page('jobs');toast('Draft and photos deleted')}
async function copyProposal(){const text=$('#proposalText').value;if(!text)return toast('No proposal to copy');await navigator.clipboard.writeText(text);toast('Proposal copied')}
function saveActiveEdits(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return;job.customer=$('#reviewCustomer').value.trim()||'Untitled Proposal';job.description=$('#reviewDescription').value.trim();job.proposal=$('#proposalText').value;job.recipient=$('#proposalRecipient').value.trim();job.missingAnswers=Object.fromEntries($$('[data-missing-answer]').map(input=>[input.dataset.missingAnswer,input.value.trim()]).filter(([,value])=>value));job.updated=Date.now();$('#reviewTitle').textContent=job.customer;persist()}
function proposalDocument(){const job=jobs.find(j=>j.id===activeJobId);if(!job)return'';const contact=[company.salesperson,company.phone,company.email].filter(Boolean).join(' · ');return `<header class="proposal-head"><div><h1>${escapeHTML(company.name||'Albert DTS')}</h1><p>${escapeHTML(contact)}</p></div><strong>PROPOSAL</strong></header><div class="proposal-meta"><p><b>Prepared for</b><br>${escapeHTML(job.customer)}</p><p><b>Project</b><br>${escapeHTML(job.type)}</p><p><b>Date</b><br>${new Date().toLocaleDateString()}</p></div><div class="proposal-body">${escapeHTML($('#proposalText').value).replace(/\n/g,'<br>')}</div>${company.warranty?`<section><h3>Warranty</h3><p>${escapeHTML(company.warranty)}</p></section>`:''}${company.terms?`<section><h3>Terms and exclusions</h3><p>${escapeHTML(company.terms)}</p></section>`:''}<div class="signature"><span>Customer approval / signature</span><span>Date</span></div>`}
function previewProposal(){if(!$('#proposalText').value.trim())return toast('Generate or enter a proposal first');saveActiveEdits();$('#printDocument').innerHTML=proposalDocument();$('#printPreview').classList.add('open');$('#printPreview').setAttribute('aria-hidden','false')}
function closePreview(){$('#printPreview').classList.remove('open');$('#printPreview').setAttribute('aria-hidden','true')}
async function shareProposal(){const job=jobs.find(j=>j.id===activeJobId),text=$('#proposalText').value.trim();if(!job||!text)return toast('Generate or enter a proposal first');saveActiveEdits();const share={title:`Proposal for ${job.customer}`,text:`${company.name||'Albert DTS'}\n\n${text}`};if(navigator.share){try{await navigator.share(share);return}catch(error){if(error.name==='AbortError')return}}await navigator.clipboard.writeText(share.text);toast('Proposal copied for sharing')}
function loadCompanyForm(){$('#companyName').value=company.name||'';$('#salesperson').value=company.salesperson||'';$('#companyPhone').value=company.phone||'';$('#companyEmail').value=company.email||'';$('#companyWarranty').value=company.warranty||'';$('#companyTerms').value=company.terms||''}
function saveCompany(event){event.preventDefault();company={name:$('#companyName').value.trim(),salesperson:$('#salesperson').value.trim(),phone:$('#companyPhone').value.trim(),email:$('#companyEmail').value.trim(),warranty:$('#companyWarranty').value.trim(),terms:$('#companyTerms').value.trim()};persistCompany();toast('Company profile saved')}
function renderLearning(){const el=$('#learningStatus');if(el)el.textContent=learning.length?`${learning.length} approved example${learning.length===1?'':'s'} · ${learning.filter(x=>x.corrected).length} corrected`:'No approved examples yet'}
function resetLearning(){if(!learning.length)return toast('Albert has no saved learning yet');if(!confirm('Reset Albert learning from approved proposals? Saved jobs will remain.'))return;learning=[];localStorage.removeItem('albert.learning');renderLearning();toast('Albert learning reset')}
function outlookSession(){try{return JSON.parse(sessionStorage.getItem('albert.outlook')||'null')}catch{return null}}
function setOutlookSession(v){if(v)sessionStorage.setItem('albert.outlook',JSON.stringify(v));else sessionStorage.removeItem('albert.outlook');renderOutlook()}
function randomUrlSafe(n=32){const d=crypto.getRandomValues(new Uint8Array(n));return btoa(String.fromCharCode(...d)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256UrlSafe(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return btoa(String.fromCharCode(...new Uint8Array(h))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
const outlookRedirect=()=>`${location.origin}${location.pathname}`;
async function loadOutlookConfig(){try{outlookConfig=await(await fetch('/.netlify/functions/outlook-config',{cache:'no-store'})).json()}catch{outlookConfig={configured:false}}renderOutlook();return outlookConfig}
function renderOutlook(){const s=outlookSession(),status=$('#outlookStatus');if(!status)return;const connected=s?.accessToken&&s.expiresAt>Date.now();status.textContent=connected?`Connected as ${s.email||'Microsoft Outlook'}`:outlookConfig?.configured?'Not connected':'Microsoft setup required';$('#connectOutlook').classList.toggle('hidden',connected);$('#disconnectOutlook').classList.toggle('hidden',!connected)}
async function connectOutlook(){const c=outlookConfig||await loadOutlookConfig();if(!c.configured)return toast('Microsoft connection needs its App ID added in Netlify');const verifier=randomUrlSafe(64),state=randomUrlSafe(24);sessionStorage.setItem('albert.outlook.verifier',verifier);sessionStorage.setItem('albert.outlook.state',state);const p=new URLSearchParams({client_id:c.clientId,response_type:'code',redirect_uri:outlookRedirect(),response_mode:'query',scope:'openid profile User.Read Mail.Read Mail.Send',state,code_challenge:await sha256UrlSafe(verifier),code_challenge_method:'S256',prompt:'select_account'});location.assign(`https://login.microsoftonline.com/${encodeURIComponent(c.tenant)}/oauth2/v2.0/authorize?${p}`)}
async function finishOutlookSignIn(){const p=new URLSearchParams(location.search),code=p.get('code');if(!code)return;const state=p.get('state'),expected=sessionStorage.getItem('albert.outlook.state'),verifier=sessionStorage.getItem('albert.outlook.verifier');history.replaceState({},'',outlookRedirect());if(state!==expected||!verifier)return toast('Outlook sign-in could not be verified');try{const c=outlookConfig||await loadOutlookConfig(),body=new URLSearchParams({client_id:c.clientId,grant_type:'authorization_code',code,redirect_uri:outlookRedirect(),code_verifier:verifier,scope:'openid profile User.Read Mail.Read Mail.Send'}),tr=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(c.tenant)}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body}),token=await tr.json();if(!tr.ok)throw Error('Microsoft sign-in failed');const pr=await fetch('https://graph.microsoft.com/v1.0/me?$select=displayName,mail,userPrincipalName',{headers:{authorization:`Bearer ${token.access_token}`}}),profile=await pr.json();if(!pr.ok)throw Error('Could not read the Outlook account');setOutlookSession({accessToken:token.access_token,expiresAt:Date.now()+Math.max(60,token.expires_in-120)*1000,email:profile.mail||profile.userPrincipalName||'',name:profile.displayName||''});toast('Outlook connected')}catch(e){setOutlookSession(null);toast(e.message)}finally{sessionStorage.removeItem('albert.outlook.verifier');sessionStorage.removeItem('albert.outlook.state')}}
function disconnectOutlook(){setOutlookSession(null);toast('Outlook disconnected')}
async function graphFetch(url,options={}){const s=outlookSession();if(!s?.accessToken||s.expiresAt<=Date.now())throw Error('Connect Outlook first');const headers={authorization:`Bearer ${s.accessToken}`,...(options.headers||{})},r=await fetch(url,{...options,headers});if(r.status===401){setOutlookSession(null);throw Error('Outlook session expired—connect again')}return r}
async function emailWithOutlook(){const job=jobs.find(j=>j.id===activeJobId),recipient=$('#proposalRecipient').value.trim();if(!job?.proposal?.trim())return toast('Generate a proposal first');if(job.status!=='Approved')return toast('Approve the proposal before emailing it');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient))return toast('Add the customer email address');saveActiveEdits();const b=$('#emailOutlook');b.disabled=true;try{const r=await graphFetch('https://graph.microsoft.com/v1.0/me/sendMail',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:{subject:`DTS Proposal — ${job.customer}`,body:{contentType:'HTML',content:`<p>Please find the DTS proposal below.</p>${proposalDocument()}`},toRecipients:[{emailAddress:{address:recipient}}]},saveToSentItems:true})});if(!r.ok)throw Error('Outlook could not send the proposal');toast('Proposal sent through Outlook')}catch(e){toast(e.message)}finally{b.disabled=false}}
async function readOutlookMessage(id){const r=await graphFetch(`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(id)}?$select=subject,from,body,receivedDateTime`,{headers:{prefer:'outlook.body-content-type="text"'}}),m=await r.json();if(!r.ok)throw Error('Could not read that Outlook email');return m}
async function loadOutlookInbox(){const b=$('#loadOutlookInbox'),list=$('#outlookInbox');b.disabled=true;try{const r=await graphFetch('https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$top=10&$select=id,subject,from,receivedDateTime,bodyPreview&$orderby=receivedDateTime%20desc'),d=await r.json();if(!r.ok)throw Error('Could not read the Outlook inbox');list.innerHTML=(d.value||[]).map(m=>`<article class="outlook-message"><b>${escapeHTML(m.subject||'No subject')}</b><small>${escapeHTML(m.from?.emailAddress?.name||m.from?.emailAddress?.address||'Unknown sender')}</small><small>${escapeHTML(m.bodyPreview||'')}</small><div class="message-actions"><button class="secondary" data-import-message="${escapeHTML(m.id)}">Make proposal</button><button class="outlook" data-reply-message="${escapeHTML(m.id)}">Draft reply</button></div></article>`).join('')||'<div class="empty">No recent messages.</div>';list.classList.remove('hidden');$$('[data-import-message]').forEach(x=>x.onclick=()=>importOutlookMessage(x.dataset.importMessage));$$('[data-reply-message]').forEach(x=>x.onclick=()=>draftOutlookReply(x.dataset.replyMessage))}catch(e){toast(e.message)}finally{b.disabled=false}}
async function importOutlookMessage(id){try{const m=await readOutlookMessage(id),s=m.from?.emailAddress||{},job={id:crypto.randomUUID(),customer:s.name||m.subject||'Outlook request',description:`Email subject: ${m.subject||'No subject'}\n\n${m.body?.content||''}`.trim(),type:'Outlook email request',summary:m.subject||'',questions:[],missingAnswers:{},status:'Draft',proposal:'',recipient:s.address||'',source:{kind:'outlook',messageId:id},updated:Date.now()};jobs.unshift(job);persist();renderJobs();openJob(job.id);toast('Outlook email added as a new draft')}catch(e){toast(e.message)}}
async function draftOutlookReply(id){const panel=$('#outlookReplyPanel'),text=$('#outlookReplyText');panel.classList.remove('hidden');text.value='Albert is drafting a reply…';text.disabled=true;try{const m=await readOutlookMessage(id),s=m.from?.emailAddress||{},r=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'emailReply',from:`${s.name||''} <${s.address||''}>`,subject:m.subject||'',body:m.body?.content||'',senderName:company.salesperson||'Albert Mendoza'})}),d=await r.json();if(!r.ok)throw Error(d.error||'Albert could not draft the reply');outlookReplyContext={messageId:id};$('#outlookReplyTitle').textContent=`Reply: ${m.subject||'No subject'}`;$('#outlookReplyTo').textContent=`To: ${s.name||s.address||'Customer'}`;text.value=d.reply||''}catch(e){panel.classList.add('hidden');toast(e.message)}finally{text.disabled=false}}
function cancelOutlookReply(){outlookReplyContext=null;$('#outlookReplyText').value='';$('#outlookReplyPanel').classList.add('hidden')}
async function sendOutlookReply(){const comment=$('#outlookReplyText').value.trim();if(!outlookReplyContext||!comment)return toast('Review the reply first');const b=$('#sendOutlookReply');b.disabled=true;try{const r=await graphFetch(`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(outlookReplyContext.messageId)}/reply`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({comment})});if(!r.ok)throw Error('Outlook could not send the reply');cancelOutlookReply();toast('Customer reply sent through Outlook')}catch(e){toast(e.message)}finally{b.disabled=false}}
function renderKnowledge(){const standards=knowledge.flatMap(item=>item.reusableStandards||item.standards||[]);$('#knowledgeCount').textContent=knowledge.length;$('#knowledgePlural').textContent=knowledge.length===1?'':'s';$('#standardCount').textContent=standards.length}
function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(file)})}
function photoDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('albert.photos',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('photos')){const store=db.createObjectStore('photos',{keyPath:'id'});store.createIndex('jobId','jobId')}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function photoStore(mode='readonly'){const db=await photoDB();return{db,store:db.transaction('photos',mode).objectStore('photos')}}
async function allPhotos(){const {db,store}=await photoStore();const request=store.getAll();const photos=await new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return photos}
function blobBase64(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(blob)})}
function base64Blob(base64,type){const bytes=atob(base64),parts=[];for(let offset=0;offset<bytes.length;offset+=8192){const chunk=bytes.slice(offset,offset+8192),array=new Uint8Array(chunk.length);for(let i=0;i<chunk.length;i++)array[i]=chunk.charCodeAt(i);parts.push(array)}return new Blob(parts,{type:type||'image/jpeg'})}
async function createBackup(){const button=$('#backupDrive'),status=$('#backupStatus');button.disabled=true;button.textContent='Preparing secure backup…';try{const local={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('albert.'))local[key]=localStorage.getItem(key)}const photos=[];for(const photo of await allPhotos())photos.push({id:photo.id,jobId:photo.jobId,name:photo.name,type:photo.type,created:photo.created,base64:await blobBase64(photo.blob)});const backup={format:'albert-dts-backup',version:1,created:new Date().toISOString(),local,photos};const file=new File([JSON.stringify(backup)],`Albert-DTS-Backup-${new Date().toISOString().slice(0,10)}.json`,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Albert DTS Backup',text:'Save this Albert DTS backup to Google Drive.',files:[file]});status.textContent='Backup ready. Confirm that Google Drive saved the file.'}else{const url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Backup downloaded. Move the file to Google Drive for safekeeping.'}}catch(error){if(error.name!=='AbortError')status.textContent='Backup could not be created. Please try again.'}finally{button.disabled=false;button.textContent='Back Up to Google Drive'}}
async function restoreBackup(event){const file=event.target.files[0],status=$('#backupStatus');event.target.value='';if(!file)return;try{if(file.size>100_000_000)throw Error('Backup too large');const backup=JSON.parse(await file.text());if(backup.format!=='albert-dts-backup'||backup.version!==1||!backup.local||!Array.isArray(backup.photos))throw Error('Invalid backup');if(!confirm(`Restore this Albert backup from ${backup.created?new Date(backup.created).toLocaleString():'an earlier date'}? It will replace Albert data on this device.`))return;for(const key of Object.keys(localStorage))if(key.startsWith('albert.'))localStorage.removeItem(key);for(const [key,value] of Object.entries(backup.local))if(key.startsWith('albert.')&&typeof value==='string')localStorage.setItem(key,value);const {db,store}=await photoStore('readwrite');store.clear();for(const photo of backup.photos){if(photo.id&&photo.jobId&&photo.base64)store.put({id:photo.id,jobId:photo.jobId,name:photo.name||'Restored photo',type:photo.type||'image/jpeg',created:Number(photo.created)||Date.now(),blob:base64Blob(photo.base64,photo.type)})}await new Promise((resolve,reject)=>{store.transaction.oncomplete=resolve;store.transaction.onerror=()=>reject(store.transaction.error)});db.close();status.textContent='Backup restored. Reloading Albert…';setTimeout(()=>location.reload(),700)}catch{status.textContent='That file is not a valid Albert DTS backup.'}}
async function compressPhoto(file){const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise(resolve=>canvas.toBlob(blob=>resolve(blob||file),'image/jpeg',.82))}
async function savePhotos(files){if(!photoJobId)return toast('Choose a job before adding photos');$('#photoStatus').textContent='Saving photos…';try{const prepared=[];for(const file of files){let blob;try{blob=await compressPhoto(file)}catch{blob=file}prepared.push({id:crypto.randomUUID(),jobId:photoJobId,name:file.name||'Job photo',type:blob.type,blob,created:Date.now()})}const {db,store}=await photoStore('readwrite');prepared.forEach(photo=>store.put(photo));await new Promise((resolve,reject)=>{store.transaction.oncomplete=resolve;store.transaction.onerror=()=>reject(store.transaction.error)});db.close();await renderPhotos();toast(`${files.length} photo${files.length===1?'':'s'} saved to job`)}catch(error){$('#photoStatus').textContent='Photo could not be saved. Try a smaller image.'}}
async function getJobPhotos(jobId){if(!jobId)return[];const {db,store}=await photoStore();const request=store.index('jobId').getAll(jobId);const photos=await new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return photos.sort((a,b)=>a.created-b.created)}
async function removePhoto(id){const {db,store}=await photoStore('readwrite');store.delete(id);await new Promise((resolve,reject)=>{store.transaction.oncomplete=resolve;store.transaction.onerror=()=>reject(store.transaction.error)});db.close();renderPhotos();toast('Photo removed')}
async function deleteJobPhotos(jobId){const photos=await getJobPhotos(jobId);if(!photos.length)return;const {db,store}=await photoStore('readwrite');photos.forEach(photo=>store.delete(photo.id));await new Promise(resolve=>store.transaction.oncomplete=resolve);db.close()}
function renderPhotoJobOptions(){const select=$('#photoJob'),open=$('#openPhotoJob');if(!jobs.length){select.innerHTML='<option value="">Start or save a proposal first</option>';select.disabled=true;open.disabled=true;photoJobId='';return}select.disabled=false;open.disabled=false;if(!jobs.some(job=>job.id===photoJobId))photoJobId=activeJobId&&jobs.some(job=>job.id===activeJobId)?activeJobId:jobs[0].id;select.innerHTML=jobs.map(job=>`<option value="${escapeHTML(job.id)}">${escapeHTML(job.customer||'Untitled Proposal')} — ${escapeHTML(job.type||'Unclassified')}</option>`).join('');select.value=photoJobId;localStorage.setItem('albert.photoJob',photoJobId)}
async function renderPhotos(){photoURLs.forEach(URL.revokeObjectURL);photoURLs=[];const el=$('#thumbs');if(!photoJobId){el.innerHTML='<div class="empty">Select a saved job before adding photos.</div>';$('#photoStatus').textContent='';return}try{const photos=await getJobPhotos(photoJobId);el.innerHTML=photos.length?photos.map(photo=>{const url=URL.createObjectURL(photo.blob);photoURLs.push(url);return`<div class="photo-card"><img alt="${escapeHTML(photo.name)}" src="${url}"><button class="remove-photo" data-remove-photo="${escapeHTML(photo.id)}" aria-label="Remove ${escapeHTML(photo.name)}">×</button><small>${escapeHTML(photo.name)}</small><button class="teach-photo" data-teach-photo="${escapeHTML(photo.id)}">Teach Albert From This</button></div>`}).join(''):'<div class="empty">No photos saved for this job yet.</div>';$$('[data-remove-photo]').forEach(button=>button.onclick=()=>removePhoto(button.dataset.removePhoto));$$('[data-teach-photo]').forEach(button=>button.onclick=()=>learnPhoto(button.dataset.teachPhoto,button));$('#photoStatus').textContent=photos.length?`${photos.length} saved photo${photos.length===1?'':'s'} · Safe after refresh`:'Photos will save automatically.'}catch{$('#photoStatus').textContent='Saved photos could not be loaded.'}}
const TRAINING_TYPES=new Set(['application/pdf','text/plain','image/jpeg','image/png','image/webp','image/gif']);
function validTrainingFile(file){return file.size<=4_000_000&&TRAINING_TYPES.has(file.type)}
async function extractKnowledge(file,category){if(!validTrainingFile(file))throw Error('Use PDF, text, or image under 4 MB');const base64=await fileBase64(file);const response=await fetch('/.netlify/functions/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'knowledge',category,file:{type:file.type,base64}})});const data=await response.json();if(!response.ok)throw Error(data.error||'Extraction failed');const result=data.knowledge||{},confidence=Number(result.confidence);if(result.needsReview||!Number.isFinite(confidence)||confidence<0.8)throw Error(result.reviewReason||'Low-confidence or unreadable content needs review');const standards=[...(result.standards||[]),...(result.warrantyTerms||[]),...(result.exclusions||[])].filter(Boolean);if(!standards.length)throw Error('No reusable standards found');return{standards,counts:{standards:(result.standards||[]).length,warrantyTerms:(result.warrantyTerms||[]).length,exclusions:(result.exclusions||[]).length}}}
async function trainFile(file,category='Approved Proposal'){const extracted=await extractKnowledge(file,category);knowledge.unshift({id:crypto.randomUUID(),schemaVersion:2,category,sourceCount:1,version:1,approvedAt:Date.now(),updated:Date.now(),standards:extracted.standards,reusableStandards:extracted.standards,counts:extracted.counts});persistKnowledge();renderKnowledge();return extracted.standards.length}
async function learnPhoto(id,button){const photos=await getJobPhotos(photoJobId),photo=photos.find(item=>item.id===id);if(!photo)return toast('Photo could not be found');button.disabled=true;try{const file=new File([photo.blob],'proposal-photo.jpg',{type:photo.type||photo.blob.type});await stageFiles([file],'Approved Proposal');button.textContent='✓ Staged for approval';toast('Photo staged. Open Settings and approve training.')}catch(error){button.disabled=false;button.textContent='Try Staging Again';toast(error.message)} }
function knowledgeDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('albert.knowledge.queue',1);request.onupgradeneeded=()=>request.result.createObjectStore('files',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function queueTransaction(mode,work){const db=await knowledgeDB(),store=db.transaction('files',mode).objectStore('files');work(store);await new Promise((resolve,reject)=>{store.transaction.oncomplete=resolve;store.transaction.onerror=()=>reject(store.transaction.error)});db.close()}
async function loadKnowledgeQueue(){const db=await knowledgeDB(),store=db.transaction('files').objectStore('files'),request=store.getAll();knowledgeQueue=await new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();knowledgeQueue.sort((a,b)=>a.stagedAt-b.stagedAt);renderKnowledgeQueue()}
function renderKnowledgeQueue(){const el=$('#knowledgeQueue');el.innerHTML=knowledgeQueue.length?knowledgeQueue.map(item=>`<div class="queue-row"><span><b>${escapeHTML(item.label||'Staged source')}</b><small>${escapeHTML(item.category)} · ${escapeHTML(item.type||'file')}</small></span><span class="queue-status">${escapeHTML(item.status||'Ready')}</span></div>`).join(''):'<div class="empty">No files staged. Nothing is sent until you confirm.</div>';$('#teachQueued').disabled=!knowledgeQueue.length||knowledgeQueue.some(item=>item.status==='Processing');$('#clearQueue').disabled=!knowledgeQueue.length}
async function stageFiles(files,category){const accepted=[],rejected=files.filter(file=>!validTrainingFile(file)).length;for(const file of files){if(validTrainingFile(file)){const image=file.type.startsWith('image/');accepted.push({id:crypto.randomUUID(),label:image?'Proposal picture':'Proposal document',type:file.type,category,status:'Ready',stagedAt:Date.now(),blob:file})}}if(accepted.length){await queueTransaction('readwrite',store=>accepted.forEach(item=>store.put(item)));knowledgeQueue.push(...accepted);renderKnowledgeQueue()}toast(`${accepted.length} source${accepted.length===1?'':'s'} staged${rejected?` · ${rejected} skipped`:''}`)}
async function stageKnowledge(event){await stageFiles([...event.target.files],$('#knowledgeCategory').value);event.target.value=''}
async function clearKnowledgeQueue(){if(!knowledgeQueue.length)return;await queueTransaction('readwrite',store=>store.clear());knowledgeQueue=[];renderKnowledgeQueue();$('#knowledgeProgress').classList.add('hidden');toast('Staged files cleared')}
async function teachQueuedKnowledge(){if(!knowledgeQueue.length)return;const progress=$('#knowledgeProgress');progress.classList.remove('hidden');progress.innerHTML=`<b>Teaching Albert from ${knowledgeQueue.length} approved source${knowledgeQueue.length===1?'':'s'}…</b><p>Keep Settings open until extraction finishes.</p>`;let added=0,failed=0;$('#teachQueued').disabled=true;$('#clearQueue').disabled=true;for(const item of [...knowledgeQueue]){item.status='Processing';renderKnowledgeQueue();try{await trainFile(new File([item.blob],'approved-source',{type:item.type}),item.category);await queueTransaction('readwrite',store=>store.delete(item.id));knowledgeQueue=knowledgeQueue.filter(queued=>queued.id!==item.id);added++}catch(error){item.status=String(error.message||'Needs review').slice(0,80);await queueTransaction('readwrite',store=>store.put(item));failed++}renderKnowledgeQueue()}progress.innerHTML=`<b>${added?`${added} approved source${added===1?'':'s'} successfully taught`:'No learning was approved'}</b><p>${failed?`${failed} staged source${failed===1?'':'s'} remain for review or retry. Nothing low-confidence was learned.`:'Extraction succeeded. Raw queued files were removed; only reusable standards remain on this device.'}</p>`;renderKnowledgeQueue()}
function clearKnowledge(){if(!knowledge.length)return toast('Albert has no training to clear');if(!confirm('Clear all private Albert training from this device?'))return;knowledge=[];persistKnowledge();renderKnowledge();$('#knowledgeProgress').classList.add('hidden');toast('Private training cleared')}
function finishVoice(){voiceListening=false;voiceRecognition=null;$('#voiceBtn').textContent='🎙️ Start speaking';$('#voiceBtn').setAttribute('aria-pressed','false');score();saveIntake()}
function voiceErrorMessage(error){return({not_allowed:'Allow microphone access in your browser settings, then try again',service_not_allowed:'Voice dictation is blocked in this browser',audio_capture:'No microphone was found',network:'Voice dictation needs an internet connection',no_speech:'I did not hear anything—tap and speak again',aborted:'Recording stopped'}[error]||'Voice dictation could not start')}
function toggleVoice(){if(voiceListening&&voiceRecognition){voiceRecognition.stop();return}const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return toast('Use your keyboard microphone—this browser does not support in-app dictation');voiceBase=$('#description').value.trim();let finalText='';voiceRecognition=new Recognition();voiceRecognition.lang='en-US';voiceRecognition.continuous=!/iPhone|iPad|iPod/i.test(navigator.userAgent);voiceRecognition.interimResults=true;voiceRecognition.maxAlternatives=1;voiceRecognition.onstart=()=>{voiceListening=true;$('#voiceBtn').textContent='■ Stop and use notes';$('#voiceBtn').setAttribute('aria-pressed','true');toast('Listening… speak naturally')};voiceRecognition.onresult=event=>{let interim='';for(let i=event.resultIndex;i<event.results.length;i++){const words=event.results[i][0].transcript.trim();if(event.results[i].isFinal)finalText+=(finalText?' ':'')+words;else interim+=(interim?' ':'')+words}const spoken=[finalText,interim].filter(Boolean).join(' ');$('#description').value=[voiceBase,spoken].filter(Boolean).join(voiceBase&&spoken?' ':'');score();saveIntake()};voiceRecognition.onerror=event=>{if(event.error!=='aborted')toast(voiceErrorMessage(event.error))};voiceRecognition.onend=finishVoice;try{voiceRecognition.start()}catch{finishVoice();toast('Tap the microphone once, then speak after it says Listening') }}

$$('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#tellAlbert').onclick=()=>{resetIntake();page('intake')};$('#viewJobs').onclick=()=>page('jobs');$$('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='new'){resetIntake();page('projects');return}page({camera:'camera',drafts:'jobs',teach:'teach',home:'home',jobs:'jobs'}[b.dataset.action])});
const cats=['All',...new Set(PROJECTS.map(x=>x[0]))];$('#categoryChips').innerHTML=cats.map(c=>`<button class="${c==='All'?'active':''}">${c}</button>`).join('');$$('#categoryChips button').forEach(b=>b.onclick=()=>{category=b.textContent;$$('#categoryChips button').forEach(x=>x.classList.toggle('active',x===b));renderProjects()});$('#projectSearch').oninput=renderProjects;$('#customer').oninput=()=>{score();saveIntake()};$('#description').oninput=()=>{score();saveIntake()};$('#reviewCustomer').oninput=saveActiveEdits;$('#reviewDescription').oninput=saveActiveEdits;$('#proposalText').oninput=saveActiveEdits;$('#proposalRecipient').oninput=saveActiveEdits;$('#blankProposal').onclick=blankProposal;$('#projectTemplate').onclick=()=>{resetIntake();page('projects')};$('#analyzeBtn').onclick=analyze;$('#generateProposal').onclick=generateProposal;$('#approveProposal').onclick=approveProposal;$('#deleteDraft').onclick=deleteDraft;$('#copyProposal').onclick=copyProposal;$('#previewProposal').onclick=previewProposal;$('#shareProposal').onclick=shareProposal;$('#emailOutlook').onclick=emailWithOutlook;$('#connectOutlook').onclick=connectOutlook;$('#disconnectOutlook').onclick=disconnectOutlook;$('#loadOutlookInbox').onclick=loadOutlookInbox;$('#cancelOutlookReply').onclick=cancelOutlookReply;$('#sendOutlookReply').onclick=sendOutlookReply;$('#resetLearning').onclick=resetLearning;$('#closePreview').onclick=closePreview;$('#printProposal').onclick=()=>print();$('#companyForm').onsubmit=saveCompany;
$('#voiceBtn').onclick=toggleVoice;
$('#photoJob').onchange=event=>{photoJobId=event.target.value;localStorage.setItem('albert.photoJob',photoJobId);renderPhotos()};
$('#openPhotoJob').onclick=()=>{if(photoJobId)openJob(photoJobId);else toast('Choose a saved job first')};
async function handlePhotoSelection(event){const files=[...event.target.files];if(files.length)await savePhotos(files);event.target.value=''}
$('#takePhoto').onchange=handlePhotoSelection;
$('#choosePhotos').onchange=handlePhotoSelection;
$('#openTeachAlbert').onclick=()=>{const panel=$('#teachAlbertPanel');panel.open=true;panel.scrollIntoView({behavior:'smooth',block:'start'})};
$('#knowledge').onchange=stageKnowledge;
$('#knowledgeFolder').onchange=stageKnowledge;
$('#knowledgeImages').onchange=stageKnowledge;
$('#knowledgeCamera').onchange=stageKnowledge;
$('#teachQueued').onclick=teachQueuedKnowledge;
$('#clearQueue').onclick=clearKnowledgeQueue;
$('#clearKnowledge').onclick=clearKnowledge;
$('.owner-training').insertAdjacentHTML('beforebegin','<section class="drive-backup"><p class="eyebrow">BACKUP</p><h3>Google Drive Backup</h3><p class="muted">Protect every job, proposal, photo, company setting, and Albert training rule. On your phone, choose Google Drive from the secure share sheet.</p><button id="backupDrive" class="primary full-button" type="button">Back Up to Google Drive</button><label class="restore-backup">Restore a previous backup<input id="restoreBackup" type="file" accept="application/json,.json"></label><p id="backupStatus" class="fine-print muted">Nothing is sent until you choose where to save it.</p></section>');
$('#backupDrive').onclick=createBackup;
$('#restoreBackup').onchange=restoreBackup;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installApp').classList.remove('hidden')});$('#installApp').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').classList.add('hidden')};
renderJobs();renderProjects();restoreIntake();loadCompanyForm();renderKnowledge();renderLearning();loadOutlookConfig().then(finishOutlookSignIn);loadKnowledgeQueue().catch(()=>toast('The staged knowledge queue could not be opened'));if(!('webkitdirectory'in $('#knowledgeFolder'))){$('#folderPickerLabel').classList.add('hidden');$('#folderSupport').textContent='Folder selection is unavailable in this browser. Select multiple files instead.'}const restoredJob=localStorage.getItem('albert.activeJob'),restoredPage=localStorage.getItem('albert.page');if(restoredPage==='review'&&jobs.some(job=>job.id===restoredJob))openJob(restoredJob);else if(['jobs','camera','settings'].includes(restoredPage))page(restoredPage);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
